DROP DATABASE IF EXISTS atm_db;
CREATE DATABASE IF NOT EXISTS atm_db;
CREATE USER IF NOT EXISTS 'atm_user'@'localhost' IDENTIFIED BY 'atm_pwd';
GRANT ALL PRIVILEGES ON atm_db.* TO 'atm_user'@'localhost';
FLUSH PRIVILEGES;
